version: '3.7'

services:
  web:
    container_name: ride_sharing_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${PORT}:${PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true